name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: NEWBIE/Presentation\ page
